# Site
title:              FOSS
bio:                'Jekyll version of the Massively theme by HTML5UP'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             en_US
baseurl: "/foss-blog/"
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            amfoss_in
facebook:           amfoss.in
instagram:          amfoss_
github:             amfoss

# personal
location:           Amrita School of Engineering, Amritapuri, Kerala.
phone:              09567543876
email:              amritapurifoss@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
# Authors
authors:
  Manikishan:
    name: Manikishan Ghantasala
    display_name: Manikishan
    gravatar: ffcff9e55f886bcf46c534a2996937d6
    email: manikishanghantasala@gmail.com
    web: https://manikisha.wordpress.com
    twitter: https://twitter.com/ManikishanG
    description: "Author of this site"
  Bhanu prakash:
    name: Bhanu Prakash Poluparthi
    display_name: Bhanu prakash
    gravatar: a0a27865017dd4456f47f0a9e7d964a6
    email: p.bhanuprakash12345@gmail.com
    web: https://bhanuprakashnani.wordpress.com
    description: "Author of this site"
  Gopa vasanth:
    name: Gopa vasanth
    display_name: Gopa vasanth
    gravatar: 287f5d0360b37dd1ea03339b4aed1812
    email: gopavasanth1999@gmail.com
    web: https://gopavasanth.wordpress.com
    description: "Author of this site"
